server.port=8081

spring.application.name=tochookpi

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.org.springframework.security=DEBUG
